# Generated by Django 4.0.2 on 2022-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ltpc', models.CharField(max_length=20)),
                ('sem1', models.CharField(default="blank", max_length=5)),
                ('sem2', models.CharField(default="blank", max_length=5)),
                ('sem3', models.CharField(default="blank", max_length=5)),
                ('sem4', models.CharField(default="blank", max_length=5)),
                ('sem5', models.CharField(default="blank", max_length=5)),
                ('sem6', models.CharField(default="blank", max_length=5)),
                ('sem7', models.CharField(default="blank", max_length=5)),
                ('sem8', models.CharField(default="blank", max_length=5)),
                ('type', models.TextField(default="blank")),
            ],
        ),
    ]
