# Generated by Django 4.0.2 on 2022-02-26 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('semester', models.CharField(max_length=5)),
                ('ltpc', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('current_user', models.ManyToManyField(blank=True, related_name='AlreadyApplied', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
