# Generated by Django 4.0.2 on 2022-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sem1',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem2',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem3',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem4',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem5',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem6',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem7',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem8',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.TextField(default='FE'),
        ),
    ]
