# Generated by Django 4.0.2 on 2022-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_credits'),
        ('users', '0002_profile_branch_profile_completed_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_courses',
            field=models.ManyToManyField(blank=True, related_name='current_courses', to='home.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.CharField(choices=[('sem1', '1st'), ('sem2', '2nd'), ('sem3', '3rd'), ('sem4', '4th'), ('sem5', '5th'), ('sem6', '6th'), ('sem7', '7th'), ('sem8', '8th')], default='1st', max_length=30),
        ),
    ]
